"use strict";

export const guessArray = [
  "Penis",
  "Summer",
  "Airplane",
  "Metallica",
  "German Shepherd",
  "You are gay as Fuck",
  "Huge penis",
  "Winter sucks",
  "Hangman",
  "Calculator",
  "Waterbottle",
  "Computer",
  "Keyboard",
  "Headphones",
  "Chocolate",
  "Pizza",
  "Curtain",
  "Armchair",
  "Rubix Cube",
  "Challenge",
  "Alphabet",
  "Container",
  "Photography",
  "Bones",
  "Cloth",
  "Crate",
  "Couch",
  "Rope",
  "Screwdriver",
  "Chicken",
  "Beef",
  "Ostrich",
  "Tiger",
  "Owl",
  "Lion",
  "Zoo",
  "Power outlet",
  "Buffalo Soldier",
  "By the rivers of babylon",
  "Mirror",
  "Money",
  "Yo momma so fat",
  "This is a normal sentence",
];
